name: 'Core Network Deployment'

on:
  push:
    branches:
    - development
    inputs:
      workflowPath:
        description: 'The path of the main deployment workflow.'
        required: true
        type: string
        default: "./Azure/terraform-code/high-cpu-ss/core-network"
      environment:
        description: 'The environment the resources will be deployed to.'
        required: true
        type: string
        default: 'dev'
      service:
        description: 'The service the resources will be deployed to.'
        required: true
        type: string
        default: 'hub'
      location:
        description: 'The location here the resources will be deployed'
        required: true
        type: string
        default: 'uksouth'

jobs:
  build:
    name: 'Core Network Deployment'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

  deploy-core-network:
    name: 'Deploy Core network'
    uses: './.github/workflows/azure-deployment.yml'
    with:
      workflowPath: ${{ github.event.inputs.workflowPath }}
      environment: ${{ github.event.inputs.environment }}
      service: ${{ github.event.inputs.service }}
      location: ${{ github.event.inputs.location }}
