name: 'Core Network Deployment'

on:
  push:
    branches:
    - development
  workflow_dispatch:
    inputs:
      workflowPath:
        description: 'The path of the main deployment workflow.'
        required: true
        default: "./Azure/terraform-code/high-cpu-ss/core-network"
      environment:
        description: 'The environment the resources will be deployed to.'
        required: true
        default: 'dev'
      service:
        description: 'The service the resources will be deployed to.'
        required: true
        default: 'hub'
      location:
        description: 'The location here the resources will be deployed'
        required: true
        default: 'uksouth'

jobs:
  build:
    name: 'Core Network Deployment'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Deploy Core Network"
      uses: ./.github/workflows/azure-deployment.yml@development
      with:
        workflowPath: $INPUT_workflowPath
        environment: $INPUT_environment
        service: $INPUT_service
        location: $INPUT_location
