name: Core Net Deployment Manual

on:
  workflow_dispatch:
    inputs:
      workflowPath:
        description: 'The path of the main deployment workflow.'
        required: true
        type: string
        default: "./Azure/terraform-code/high-cpu-ss/core-network"
      environment:
        description: 'The environment the resources will be deployed to.'
        required: true
        type: string
        default: 'dev'
      service:
        description: 'The service the resources will be deployed to.'
        required: true
        type: string
        default: 'hub'
      location:
        description: 'The location here the resources will be deployed'
        required: true
        type: string
        default: 'uksouth'

jobs:
  build:
    name: 'Core Network Deployment'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
  terraform:
    needs: build
    name: 'Deploy-CoreNetwork'
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}

    defaults:
      run:
        shell: bash
        working-directory: ${{github.event.inputs.workflowPath}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup-Terraform
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID 
      run: terraform init

    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID
      run: terraform plan -var-file="dev.tfvars"
