name: Core Net Deployment Manual

on:
  workflow_dispatch:
    inputs:
      workflowPath:
        description: 'The path of the main deployment workflow.'
        required: true
        type: string
        default: "./Azure/terraform-code/high-cpu-ss/core-network"
      environment:
        description: 'The environment the resources will be deployed to.'
        required: true
        type: string
        default: 'dev'
      action:
        description: 'Whether to apply or destroy the core network'
        required: true
        default: 'apply'

jobs:
  build:
    name: 'Core Network Deployment'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
  deploy-core-network:
    if: contains(github.event.inputs.action, "apply")
    needs: build 
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      workflowPath: ${{github.event.inputs.workflowPath}}
      environment: ${{github.event.inputs.environment}}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  destroy-core-network:
    if: contains(github.event.inputs.action, "destroy")
    needs: build 
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      workflowPath: ${{github.event.inputs.workflowPath}}
      environment: ${{github.event.inputs.environment}}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
